package com.felipesales007.chamadas;

import com.badlogic.gdx.audio.Music;
import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.math.Rectangle;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton;
import com.felipesales007.jogo.Jogo;

import java.util.Random;

public class Importacao
{
    public Jogo.State estado = Jogo.State.RUN;
    public SpriteBatch batch;
    public Texture logo;
    public Texture bestScore;
    public Texture fundo1;
    public Texture fundo2;
    public Texture uvaPontos;
    public Texture uvaPontosMaximo;
    public Texture newRecord;
    public Texture placa;
    public Texture[] intro;
    public Texture[] boyParado;
    public Texture[] boyCorrendo;
    public Texture[] boyPulando;
    public Texture[] boyBatida;
    public Texture[] boyQueda;
    public Texture[] gameOver;
    public Texture caquito;
    public Texture flecha;
    public Texture buraco;
    public Texture uva;
    public TextButton play;
    public TextButton pause;
    public Stage stage;
    public Stage stagePause;
    public Skin skin;
    public BitmapFont introNome;
    public BitmapFont uvaPontuacao;
    public BitmapFont uvaPontuacaoMaxima;
    public Random numeroRandomico;
    public Random flechaRandomica;

    public int obstaculoRandomico;
    public int obstaculoExtraRandomico;
    public int alturaFlecha;
    public boolean estadoFlecha = false;
    public int tempo = 0;
    public int tempoBtn = 0;
    public int tempoIntro = 0;
    public float queda = 0;
    public int caiu;
    public int uvaAtiva = 1;
    public int newPonto = 0;
    public int pontuacao = 0;
    public int pontuacaoNovo = 0;
    public int melhorPontuacao = 0;
    public boolean marcouPonto = false;
    public float nRetangulo = 6.4f;
    public float larguraDispositivo;
    public float alturaDispositivo;
    public float variacaoIntro = 0;
    public int introducaoVoz = 0;
    public float variacaoParado = 0;
    public float variacaoCorrendo = 0;
    public float variacaoPulo = 0;
    public float variacaoBatida = 0;
    public float variacaoQueda = 0;
    public float variacaoGameOver = 0;
    public float deltaTime;
    public float boyPosicao;
    public boolean pular = false;
    public int puloAtivo = 0;
    public float movimentoFundo1;
    public float movimentoFundo2;
    public int estadoJogo = 0;
    public float movimentoCaquito;
    public float movimentoFlecha;
    public float movimentoBuraco;
    public float movimentoUva;
    public float movimentoUvaDelay;
    public int vibrarAtivo = 0;
    public int somHit = 0;

    public Music musica;
    public Music musicaMenu;
    public Sound clique;
    public Music introSom;
    public Sound introVoz;
    public Sound go;
    public Sound pulo;
    public Sound au;
    public Sound quedaBuraco;
    public Sound hit;
    public Sound ponto;
    public Sound pontoRecord;
    public Sound perigo;
    public Sound record;

    public Rectangle boyRetangulo;
    public Rectangle caquitoRetangulo;
    public Rectangle buracoFrenteRetangulo;
    public Rectangle buracoMeioRetangulo;
    public Rectangle buracoFundoRetangulo;
    public Rectangle flechaRetangulo;
    public Rectangle uvaRetangulo;
    public ShapeRenderer shape;
}
